cyber: Dockerfile has better deps and added bashrc

diff --git a/docker/cyber/Dockerfile b/docker/cyber/Dockerfile
--- a/docker/cyber/Dockerfile
+++ b/docker/cyber/Dockerfile
@@ -7,6 +7,14 @@ ENV TZ=America/New_York
 
 # Update the package list and install essential tools
 RUN apt-get update && apt-get install -y --no-install-recommends \
+    bc \
+    curl \
+    wget \
+    git \
+    vim \
+    python3 \
+    python3-pip
+RUN apt-get install -y --no-install-recommends \
     nmap \
     netcat \
     tcpdump \
@@ -21,9 +29,7 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
     python3 \
     python3-pip \
     build-essential \
-    forensics-all \ 
-    && rm -rf /var/lib/apt/lists/*
-
+    forensics-all
 # Install additional Python packages for pentesting
 RUN pip3 install --no-cache-dir \
     pwntools \
@@ -32,6 +38,13 @@ RUN pip3 install --no-cache-dir \
 
 # Optional: Install Metasploit
 #RUN curl https://raw.githubusercontent.com/rapid7/metasploit-framework/master/msfinstall | sh
+
+# Configure bash environment
+WORKDIR /root
+RUN \
+	git clone --recursive https://github.com/ErezBinyamin/dotfiles.git; \
+	[ -f ~/.bashrc ] && cp ~/.bashrc ~/.bashrc.bak; \
+	printf '\n# Dotfiles: https://github.com/ErezBinyamin/dotfiles.git;\nDOTFILES=/root/dotfiles;\n[ -d ${DOTFILES} ] && source ${DOTFILES}/top.sh || echo "[ERROR] DirectoryNotFound: ${DOTFILES}";\n\n' >> ~/.bashrc;
 
 # Clean up APT when done to reduce image size
 RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
